openapi: 3.0.0
info:
  title: CNS HTTP Stream API
  version: 1.0.0
  description: API for the HTTP server 

servers:
 - url: http://localhost:3000

tags:
  - name: Streams
    description: APIs related to stream operations
  - name: Sessions
    description: APIs related to session operations
  - name: Metrics
    description: APIs related to metrics and streams

paths:
  /streams/key:
    post:
      summary: Create a new stream and return its key
      tags:
        - Streams
      responses:
        '200':
          description: New stream key generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  key:
                    type: string

  /streams:
    get:
      summary: Get the list of all streams
      tags:
        - Streams
      responses:
        '200':
          description: List of streams retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Stream'

  /streams/{id}:
    get:
      summary: Get information about a specific stream
      tags:
        - Streams
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the stream
          schema:
            type: string
      responses:
        '200':
          description: Information about the specific stream
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stream'

    post:
      summary: Notify server about a "start" event on a specific stream
      tags:
        - Streams
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the stream
          schema:
            type: string
      responses:
        '200':
          description: Event notification received

  /streams/{id}/stopped:
    post:
      summary: Notify server about a "stop" event on a specific stream
      tags:
        - Streams
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the stream
          schema:
            type: string
      responses:
        '200':
          description: Event notification received

  /streams/{id}/views:
    post:
      summary: Notify server about a "view" event on a specific stream
      tags:
        - Streams
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the stream
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                screenSize:
                  type: object
                  properties:
                    width:
                      type: number
                    height:
                      type: number
                resolution:
                  type: string
      responses:
        '200':
          description: View event registered

    get:
      summary: Get the list of all views associated with a specific stream
      tags:
        - Streams
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the stream
          schema:
            type: string
      responses:
        '200':
          description: List of views associated with the stream
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/View'

  /streams/{id}/metrics:
    post:
      summary: Send metrics associated to a stream and session
      tags:
        - Streams
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the stream
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Metrics'
      responses:
        '200':
          description: Metrics saved

    get:
      summary: Get all metrics associated with a stream and session
      tags:
        - Streams
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the stream
          schema:
            type: string
      responses:
        '200':
          description: List of metrics associated with the stream
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Metrics'
    
  /sessions:
    get:
      summary: Get the list of all sessions
      tags:
        - Sessions
      responses:
        '200':
          description: List of sessions retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

    post:
      summary: Create a new session or retrieve an existing session
      tags:
        - Sessions
      requestBody:
        required: false
        content: {}
      responses:
        '200':
          description: Session created or retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /metrics/streams:
    get:
      summary: Get aggregated metrics for a specific stream
      tags:
        - Metrics
      parameters:
        - name: id
          in: query
          required: true
          description: Stream ID
          schema:
            type: string
      responses:
        '200':
          description: Aggregated metrics for the specific stream
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AggregatedStreamMetrics'

  /metrics/sessions:
    get:
      summary: Get aggregated metrics for sessions
      tags:
        - Metrics
      parameters:
        - name: id
          in: query
          required: false
          description: Stream ID
          schema:
            type: string
      responses:
        '200':
          description: Aggregated metrics for sessions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AggregatedSessionMetrics'

components:
  schemas:
    AggregatedStreamMetrics:
      type: object
      properties:
        totalStreamedBytes:
          type: number
        totalStreamedTime:
          type: number
        viewList:
          type: array
          items:
            $ref: '#/components/schemas/View'

    AggregatedSessionMetrics:
      type: array
      items:
        type: object
        properties:
          _id:
            type: string
          mediaLevels:
            type: array
            items:
              type: object
              properties:
                level:
                  type: number
                totalStreamedTime:
                  type: number
                '%totalStreamedTime':
                  type: number
              required:
                - level
                - totalStreamedTime
                - '%totalStreamedTime'
          sessionId:
            type: string
          userAgent:
            type: string
          clientIp:
            type: string
          totalStreamedTime:
            type: number
          totalStreamedBytes:
            type: number
          bufferingEvents:
            type: number
          bufferingTime:
            type: number
          downloadRate:
            type: number
          bandwidth:
            type: number
          screenSizes:
            type: array
            items:
              type: object
              properties:
                size:
                  type: string
                totalStreamedTime:
                  type: number
                '%totalStreamedTime':
                  type: number
              required:
                - size
                - totalStreamedTime
                - '%totalStreamedTime'
    
    User:
      type: object
      properties:
        sessionId:
          type: string
        clientIp:
          type: string
        userAgent:
          type: string
        timestamp:
          type: string
    Stream:
      type: object
      properties:
        id:
          type: string
        streamKey:
          type: string
        name:
          type: string
        description:
          type: string
        ref:
          type: string
        resolutions:
          type: array
          items:
            type: string
        createdAt:
          type: string
        isLive:
          type: boolean

    View:
      type: object
      properties:
        streamId:
          type: string
        sessionId:
          type: string
        timestamp:
          type: string

    Metrics:
      type: object
      properties:
        trigger:
          type: string
        timestamp:
          type: string
        screenSize:
          type: object
          properties:
            width:
              type: number
            height:
              type: number
        mediaLevel:
          type: object
          properties:
            resolution:
              type: string
            bandwidth:
              type: number
            level:
              type: number
            media:
              type: string
        streamedTime:
          type: number
        downloadedBytes:
          type: number
        bufferings:
          type: array
          items:
            type: object
            properties:
              timestamp:
                type: string
              videoTimestamp:
                type: number
              duration:
                type: number
        downloadRate:
          type: number
        bandwidth:
          type: number
        sessionId:
          type: string
        clientIp:
          type: string
        userAgent:
          type: string
        streamId:
          type: string
